name: Build

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
    - uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

    - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: tags
      uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
      with:
        images: ghcr.io/wfg/openvpn-client
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

    - id: build-args
      run: |
        ref=${{ github.ref }}
        vpatch=${ref##refs/*/}
        patch=${vpatch#v}
        echo "::set-output name=date::$(date --utc --iso-8601=seconds)"
        echo "::set-output name=version::$patch"

    - uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
      with:
        context: "{{defaultContext}}:build"
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        build-args: |
          BUILD_DATE=${{ steps.build-args.outputs.date }}
          IMAGE_VERSION=${{ steps.build-args.outputs.version }}
        tags: ${{ steps.tags.outputs.tags }}
        push: true
